//go:build !windows

package test_test

import (
	"os"
	"path/filepath"
	"testing"

	intHclparse "github.com/gruntwork-io/terragrunt/internal/hclparse"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestStackDependenciesAutoIncludeGeneration(t *testing.T) {
	t.Parallel()

	// Copy fixture to temp dir to avoid polluting the repo
	tmpDir := t.TempDir()

	// Copy the fixture tree
	err := copyDirSimple("fixtures/stacks/stack-dependencies-autoinclude", tmpDir)
	if err != nil {
		// Fallback: use fixture directly and clean up .terragrunt-stack after
		tmpDir = "fixtures/stacks/stack-dependencies-autoinclude"
		defer os.RemoveAll(filepath.Join(tmpDir, "live", ".terragrunt-stack"))
	}

	liveDir := filepath.Join(tmpDir, "live")
	stackFile := filepath.Join(liveDir, "terragrunt.stack.hcl")

	// Read and parse the stack file with the two-pass parser
	srcBytes, err := os.ReadFile(stackFile)
	require.NoError(t, err)

	result, err := intHclparse.ParseStackFile(srcBytes, stackFile, liveDir, nil)
	require.NoError(t, err)

	// Verify units were parsed
	require.Len(t, result.Units, 2)

	// Verify autoinclude was resolved for app
	resolved, ok := result.AutoIncludes["app"]
	require.True(t, ok, "app should have autoinclude")
	require.Len(t, resolved.Dependencies, 1)
	assert.Equal(t, "vpc", resolved.Dependencies[0].Name)

	// Generate the autoinclude file
	appDir := filepath.Join(liveDir, ".terragrunt-stack", "app")

	err = intHclparse.GenerateAutoIncludeFile(resolved, appDir, srcBytes, resolved.EvalCtx)
	require.NoError(t, err)

	// Verify generated file exists
	autoIncludePath := filepath.Join(appDir, intHclparse.AutoIncludeFile)
	assert.FileExists(t, autoIncludePath)

	// Read and verify contents
	generated, err := os.ReadFile(autoIncludePath)
	require.NoError(t, err)

	content := string(generated)

	// Header comment
	assert.Contains(t, content, "Generated by Terragrunt")

	// Dependency block with relative config_path
	assert.Contains(t, content, `dependency "vpc"`)
	assert.Contains(t, content, "../vpc")

	// Mock outputs preserved
	assert.Contains(t, content, "mock_outputs_allowed_terraform_commands")
	assert.Contains(t, content, "mock-vpc-id")

	// Inputs: env evaluated to "test", vpc_id preserved as deferred
	assert.Contains(t, content, `"test"`)
	assert.NotContains(t, content, "local.env")
	assert.Contains(t, content, "dependency.vpc.outputs.vpc_id")

	// Clean up generated files
	os.RemoveAll(filepath.Join(liveDir, ".terragrunt-stack"))
}

// copyDirSimple copies a directory tree. Simple implementation for test use.
func copyDirSimple(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		relPath, _ := filepath.Rel(src, path)
		targetPath := filepath.Join(dst, relPath)

		if info.IsDir() {
			return os.MkdirAll(targetPath, info.Mode())
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		return os.WriteFile(targetPath, data, info.Mode())
	})
}
