//go:build !windows

package test_test

import (
	"os"
	"path/filepath"
	"testing"

	intHclparse "github.com/gruntwork-io/terragrunt/internal/hclparse"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/test/helpers"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestStackDependenciesAutoIncludeGeneration(t *testing.T) {
	t.Parallel()

	// Copy fixture to temp dir to avoid polluting the repo
	tmpDir := t.TempDir()

	// Copy the fixture tree
	helpers.CopyDir(t, "fixtures/stacks/stack-dependencies-autoinclude", tmpDir)

	liveDir := filepath.Join(tmpDir, "live")
	stackFile := filepath.Join(liveDir, "terragrunt.stack.hcl")

	// Read and parse the stack file with the two-pass parser
	srcBytes, err := os.ReadFile(stackFile)
	require.NoError(t, err)

	result, err := intHclparse.ParseStackFile(vfs.NewOSFS(), &intHclparse.ParseStackFileInput{Src: srcBytes, Filename: stackFile, StackDir: liveDir})
	require.NoError(t, err)

	// Verify units were parsed
	require.Len(t, result.Units, 2)

	// Verify autoinclude was resolved for app
	resolved, ok := result.AutoIncludes["app"]
	require.True(t, ok, "app should have autoinclude")
	require.Len(t, resolved.Dependencies, 1)
	assert.Equal(t, "vpc", resolved.Dependencies[0].Name)

	// Generate the autoinclude file
	appDir := filepath.Join(liveDir, ".terragrunt-stack", "app")

	err = intHclparse.GenerateAutoIncludeFile(vfs.NewOSFS(), resolved, appDir, srcBytes, resolved.EvalCtx)
	require.NoError(t, err)

	// Verify generated file exists
	autoIncludePath := filepath.Join(appDir, intHclparse.AutoIncludeFile)
	assert.FileExists(t, autoIncludePath)

	// Read and verify contents
	generated, err := os.ReadFile(autoIncludePath)
	require.NoError(t, err)

	content := string(generated)

	// Header comment
	assert.Contains(t, content, "Generated by Terragrunt")

	// Dependency block with relative config_path
	assert.Contains(t, content, `dependency "vpc"`)
	assert.Contains(t, content, "../vpc")

	// Mock outputs preserved
	assert.Contains(t, content, "mock_outputs_allowed_terraform_commands")
	assert.Contains(t, content, "mock-vpc-id")

	// Inputs: env evaluated to "test", vpc_id preserved as deferred
	assert.Contains(t, content, `"test"`)
	assert.NotContains(t, content, "local.env")
	assert.Contains(t, content, "dependency.vpc.outputs.vpc_id")

	// Clean up generated files
	os.RemoveAll(filepath.Join(liveDir, ".terragrunt-stack"))
}

func TestStackDependenciesDAGOrdering(t *testing.T) {
	t.Parallel()

	// This test verifies that the DAG correctly orders units when dependencies
	// are defined in autoinclude files. Without the fix in extractDependencyPaths
	// (reading autoinclude files for dependency config_paths), both units would
	// run in parallel, causing the dependent unit to fail.

	tmpDir := t.TempDir()

	helpers.CopyDir(t, "fixtures/stacks/stack-dependencies-autoinclude", tmpDir)

	liveDir := filepath.Join(tmpDir, "live")
	stackFile := filepath.Join(liveDir, "terragrunt.stack.hcl")

	// Step 1: Parse and generate the autoinclude file
	srcBytes, err := os.ReadFile(stackFile)
	require.NoError(t, err)

	result, err := intHclparse.ParseStackFile(vfs.NewOSFS(), &intHclparse.ParseStackFileInput{Src: srcBytes, Filename: stackFile, StackDir: liveDir})
	require.NoError(t, err)

	resolved := result.AutoIncludes["app"]
	require.NotNil(t, resolved)

	appDir := filepath.Join(liveDir, ".terragrunt-stack", "app")

	err = intHclparse.GenerateAutoIncludeFile(vfs.NewOSFS(), resolved, appDir, srcBytes, resolved.EvalCtx)
	require.NoError(t, err)

	// Step 2: Verify the generated autoinclude file can be read by the
	// discovery system for DAG construction.
	autoIncludePath := filepath.Join(appDir, intHclparse.AutoIncludeFile)
	require.FileExists(t, autoIncludePath)

	// Step 3: Use ExtractAutoIncludeDependencyPaths to verify the DAG
	// would see the dependency from unit-w-inputs → unit-w-outputs.
	depPaths, depErr := intHclparse.AutoIncludeDependencyPaths(vfs.NewOSFS(), appDir)
	require.NoError(t, depErr)

	require.Len(t, depPaths, 1, "unit-w-inputs should have exactly 1 dependency from autoinclude")

	// The dependency path should point to the vpc directory
	// (../vpc resolved relative to appDir = .terragrunt-stack/app)
	vpcDir := filepath.Join(liveDir, ".terragrunt-stack", "vpc")
	assert.Equal(t, vpcDir, depPaths[0],
		"dependency should point to vpc unit, got %s", depPaths[0])
}

func TestStackDependenciesAutoInclude_Symlink(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()

	helpers.CopyDir(t, "fixtures/stacks/stack-dependencies-autoinclude", tmpDir)

	liveDir := filepath.Join(tmpDir, "live")

	// Create a symlink to the live directory
	symlinkDir := filepath.Join(tmpDir, "symlinked-live")
	require.NoError(t, os.Symlink(liveDir, symlinkDir))

	stackFile := filepath.Join(symlinkDir, "terragrunt.stack.hcl")

	srcBytes, err := os.ReadFile(stackFile)
	require.NoError(t, err)

	// Parse via symlinked directory — should work
	result, err := intHclparse.ParseStackFile(vfs.NewOSFS(), &intHclparse.ParseStackFileInput{
		Src:      srcBytes,
		Filename: stackFile,
		StackDir: symlinkDir,
	})
	require.NoError(t, err)
	require.Len(t, result.Units, 2)

	// Autoinclude should still resolve
	resolved, ok := result.AutoIncludes["app"]
	require.True(t, ok)
	require.Len(t, resolved.Dependencies, 1)
}

func TestStackDependenciesAutoIncludeDAGWithoutAutoInclude(t *testing.T) {
	t.Parallel()

	// Verify that units WITHOUT autoinclude files return no extra dependency paths.
	tmpDir := t.TempDir()

	helpers.CopyDir(t, "fixtures/stacks/stack-dependencies-autoinclude", tmpDir)

	liveDir := filepath.Join(tmpDir, "live")
	stackFile := filepath.Join(liveDir, "terragrunt.stack.hcl")

	srcBytes, err := os.ReadFile(stackFile)
	require.NoError(t, err)

	result, err := intHclparse.ParseStackFile(vfs.NewOSFS(), &intHclparse.ParseStackFileInput{Src: srcBytes, Filename: stackFile, StackDir: liveDir})
	require.NoError(t, err)

	// Generate autoinclude only for app (vpc has no autoinclude)
	resolved := result.AutoIncludes["app"]
	require.NotNil(t, resolved)

	appDir := filepath.Join(liveDir, ".terragrunt-stack", "app")

	err = intHclparse.GenerateAutoIncludeFile(vfs.NewOSFS(), resolved, appDir, srcBytes, resolved.EvalCtx)
	require.NoError(t, err)

	// vpc unit has NO autoinclude → should return no deps
	vpcDir := filepath.Join(liveDir, ".terragrunt-stack", "vpc")
	require.NoError(t, os.MkdirAll(vpcDir, 0755))

	vpcDeps, vpcErr := intHclparse.AutoIncludeDependencyPaths(vfs.NewOSFS(), vpcDir)
	require.NoError(t, vpcErr)
	assert.Empty(t, vpcDeps, "vpc unit should have no autoinclude dependencies")
}
