package redesign_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gruntwork-io/terragrunt/internal/cli/commands/catalog/tui/redesign"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/pkg/options"
	"github.com/gruntwork-io/terragrunt/test/helpers"
	"github.com/gruntwork-io/terragrunt/test/helpers/logger"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCopyCmd_CopiesIntoWorkingDirectory(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)

	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# vpc unit\n")
	writeFile(t, filepath.Join(repoDir, "vpc", "inputs.hcl"), "# inputs\n")
	writeFile(t, filepath.Join(repoDir, "vpc", ".terragrunt-cache", "junk.txt"), "should be skipped")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)
	require.Equal(t, redesign.ComponentKindUnit, components[0].Kind)

	workingDir := t.TempDir()
	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	assert.FileExists(t, filepath.Join(workingDir, "terragrunt.hcl"))
	assert.FileExists(t, filepath.Join(workingDir, "inputs.hcl"))
	assert.NoFileExists(t, filepath.Join(workingDir, ".terragrunt-cache", "junk.txt"))
	assert.NoDirExists(t, filepath.Join(workingDir, ".terragrunt-cache"))
}

func TestCopyCmd_WritesValuesStubForUnit(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)

	unitBody := `
locals {
  region = values.region
}

inputs = {
  app = values.app
  env = values.env
}
`
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), unitBody)

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	valuesPath := filepath.Join(workingDir, "terragrunt.values.hcl")
	assert.FileExists(t, valuesPath)

	raw, err := os.ReadFile(valuesPath)
	require.NoError(t, err)

	content := string(raw)
	assert.Contains(t, content, "# Auto-generated by `terragrunt catalog`")

	appIdx := strings.Index(content, "\napp")

	envIdx := strings.Index(content, "\nenv")

	regionIdx := strings.Index(content, "\nregion")

	require.NotEqual(t, -1, appIdx)
	require.NotEqual(t, -1, envIdx)
	require.NotEqual(t, -1, regionIdx)
	assert.Less(t, appIdx, envIdx)
	assert.Less(t, envIdx, regionIdx)
}

func TestCopyCmd_LeavesExistingValuesFileAlone(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"),
		`locals { region = values.region }`)

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	existing := []byte(`region = "us-east-1"` + "\n")
	require.NoError(t, os.WriteFile(filepath.Join(workingDir, "terragrunt.values.hcl"), existing, 0o644))

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	got, err := os.ReadFile(filepath.Join(workingDir, "terragrunt.values.hcl"))
	require.NoError(t, err)
	assert.Equal(t, existing, got, "pre-existing values file should be untouched")
}

func TestCopyCmd_RefusesToOverwriteExistingFile(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "stack-a", "terragrunt.stack.hcl"), "# stack\n")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	writeFile(t, filepath.Join(workingDir, "terragrunt.stack.hcl"), "# preexisting")

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	err = redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "already exists")
}

func TestCopyCmd_RejectsNilComponent(t *testing.T) {
	t.Parallel()

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = t.TempDir()

	err := redesign.NewCopyCmd(logger.CreateLogger(), opts, nil).Run()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "nil component")
}

func TestCopyCmd_RejectsEmptyWorkingDir(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# unit\n")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = ""

	err = redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "empty working directory")
}

func TestCopyCmd_FailsWhenSourceMissing(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# unit\n")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	// Remove the source directory after discovery so the copy walk fails.
	require.NoError(t, os.RemoveAll(filepath.Join(repoDir, "vpc")))

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = t.TempDir()

	err = redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run()
	require.Error(t, err)
}

func TestCopyCmd_SkipsSymlinks(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# unit\n")
	writeFile(t, filepath.Join(repoDir, "vpc", "real.txt"), "hello\n")

	// Add a symlink inside the component; copyDir should skip it silently.
	require.NoError(t, os.Symlink("real.txt", filepath.Join(repoDir, "vpc", "link.txt")))

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	assert.FileExists(t, filepath.Join(workingDir, "real.txt"))
	assert.NoFileExists(t, filepath.Join(workingDir, "link.txt"))
}

// TestCopyCmd_WithFSUsesInjectedFilesystem verifies that WithFS returns the
// same builder and that the injected filesystem is honored during Run. The
// underlying Repo still points at the on-disk fixture (module.NewRepo only
// works against real git state), but the source reads and destination writes
// go through the injected FS.
func TestCopyCmd_WithFSUsesInjectedFilesystem(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# unit\n")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = t.TempDir()

	cmd := redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0])

	chained := cmd.WithFS(vfs.NewOSFS())
	assert.Same(t, cmd, chained, "WithFS should return the same builder for chaining")

	require.NoError(t, cmd.Run())

	// Result is now populated.
	r := cmd.Result()
	assert.NotNil(t, r, "Result should be callable after Run")
}

// TestCopyCmd_ResultZeroValueBeforeRun verifies Result is callable before Run
// and returns the zero copyResult.
func TestCopyCmd_ResultZeroValueBeforeRun(t *testing.T) {
	t.Parallel()

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = t.TempDir()

	cmd := redesign.NewCopyCmd(logger.CreateLogger(), opts, nil)

	// Result is safe to call even before Run; the returned value type
	// is opaque to external callers but must not panic.
	assert.NotPanics(t, func() { _ = cmd.Result() })
}

// TestCopyCmd_StdioSettersAreNoops verifies the tea.ExecCommand stdio setters
// are safe no-ops. The redesign CopyCmd does not read or write through these,
// but they satisfy the tea.ExecCommand interface.
func TestCopyCmd_StdioSettersAreNoops(t *testing.T) {
	t.Parallel()

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = t.TempDir()

	cmd := redesign.NewCopyCmd(logger.CreateLogger(), opts, nil)

	assert.NotPanics(t, func() {
		cmd.SetStdin(bytes.NewReader(nil))
		cmd.SetStdout(&bytes.Buffer{})
		cmd.SetStderr(&bytes.Buffer{})
	})
}
