package redesign_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gruntwork-io/terragrunt/internal/cli/commands/catalog/tui/redesign"
	"github.com/gruntwork-io/terragrunt/pkg/options"
	"github.com/gruntwork-io/terragrunt/test/helpers"
	"github.com/gruntwork-io/terragrunt/test/helpers/logger"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCopyCmd_CopiesIntoWorkingDirectory(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)

	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), "# vpc unit\n")
	writeFile(t, filepath.Join(repoDir, "vpc", "inputs.hcl"), "# inputs\n")
	writeFile(t, filepath.Join(repoDir, "vpc", ".terragrunt-cache", "junk.txt"), "should be skipped")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)
	require.Equal(t, redesign.ComponentKindUnit, components[0].Kind)

	workingDir := t.TempDir()
	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	assert.FileExists(t, filepath.Join(workingDir, "terragrunt.hcl"))
	assert.FileExists(t, filepath.Join(workingDir, "inputs.hcl"))
	assert.NoFileExists(t, filepath.Join(workingDir, ".terragrunt-cache", "junk.txt"))
	assert.NoDirExists(t, filepath.Join(workingDir, ".terragrunt-cache"))
}

func TestCopyCmd_WritesValuesStubForUnit(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)

	unitBody := `
locals {
  region = values.region
}

inputs = {
  app = values.app
  env = values.env
}
`
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"), unitBody)

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	valuesPath := filepath.Join(workingDir, "terragrunt.values.hcl")
	assert.FileExists(t, valuesPath)

	raw, err := os.ReadFile(valuesPath)
	require.NoError(t, err)

	content := string(raw)
	assert.Contains(t, content, "# Auto-generated by `terragrunt catalog`")

	appIdx := strings.Index(content, "\napp")

	envIdx := strings.Index(content, "\nenv")

	regionIdx := strings.Index(content, "\nregion")

	require.NotEqual(t, -1, appIdx)
	require.NotEqual(t, -1, envIdx)
	require.NotEqual(t, -1, regionIdx)
	assert.Less(t, appIdx, envIdx)
	assert.Less(t, envIdx, regionIdx)
}

func TestCopyCmd_LeavesExistingValuesFileAlone(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "vpc", "terragrunt.hcl"),
		`locals { region = values.region }`)

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	existing := []byte(`region = "us-east-1"` + "\n")
	require.NoError(t, os.WriteFile(filepath.Join(workingDir, "terragrunt.values.hcl"), existing, 0o644))

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	require.NoError(t, redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run())

	got, err := os.ReadFile(filepath.Join(workingDir, "terragrunt.values.hcl"))
	require.NoError(t, err)
	assert.Equal(t, existing, got, "pre-existing values file should be untouched")
}

func TestCopyCmd_RefusesToOverwriteExistingFile(t *testing.T) {
	t.Parallel()

	repoDir := helpers.TmpDirWOSymlinks(t)
	writeFile(t, filepath.Join(repoDir, "stack-a", "terragrunt.stack.hcl"), "# stack\n")

	repo := newFakeRepo(t, repoDir)

	components, err := redesign.NewComponentDiscovery().Discover(repo)
	require.NoError(t, err)
	require.Len(t, components, 1)

	workingDir := t.TempDir()
	writeFile(t, filepath.Join(workingDir, "terragrunt.stack.hcl"), "# preexisting")

	opts := options.NewTerragruntOptions()
	opts.WorkingDir = workingDir

	err = redesign.NewCopyCmd(logger.CreateLogger(), opts, components[0]).Run()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "already exists")
}
