[tools]
go = "1.26.0"
opentofu = "1.12.2"
golangci-lint = "2.11.4"
"go:github.com/goph/licensei/cmd/licensei" = "v0.9.0"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"go:golang.org/x/tools/gopls" = "v0.20.0"
"go:golang.org/x/tools/cmd/goimports" = "0.38.0"
bats = "1.13.0"
shellcheck = "0.11.0"
shfmt = "3.13.1"
jq = "1.8.1"
bun = "1.2.2"
go-junit-report = "2.1.0"
pre-commit = { version = "4.2.0", os = ["macos", "linux"] }
pipx = { version = "1.8.0", os = ["macos", "linux"] }
"pipx:codespell" = { version = "2.4.1", os = ["macos", "linux"] }

[settings]
lockfile = true
