S3:
  timeout: 1h
  include:
    names_regex:
      - "^terragrunt-test-[a-zA-Z0-9]{6}.*"
      - "^terragrunt-terralith-tfstate-[a-zA-Z0-9]{6}.*"
      - "^terragrunt-terralith-project-[a-zA-Z0-9]{6}.*"
      - "^terragrunt-getter-test-[a-zA-Z0-9]{6}.*"
      - "^terragrunt-cas-test-[a-zA-Z0-9]{6}.*"

VPC:
  include:
    names_regex:
      - "^vpc-.*"
      - "^step-.*"

EC2:
  include:
    names_regex:
      - "^single-instance$"

DynamoDB:
  include:
    names_regex:
      - "^terragrunt-test.*"
