// Package generate provides functionality for generating stacks from stack files.
package generate

import (
	"context"
	"fmt"
	"maps"
	"path/filepath"
	"runtime"
	"slices"
	"sync"

	"errors"

	"github.com/gruntwork-io/terragrunt/internal/component"
	"github.com/gruntwork-io/terragrunt/internal/configbridge"
	"github.com/gruntwork-io/terragrunt/internal/discovery"
	"github.com/gruntwork-io/terragrunt/internal/filter"
	"github.com/gruntwork-io/terragrunt/internal/util"
	"github.com/gruntwork-io/terragrunt/internal/venv"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/internal/worker"
	"github.com/gruntwork-io/terragrunt/internal/worktrees"
	"github.com/gruntwork-io/terragrunt/pkg/config"
	"github.com/gruntwork-io/terragrunt/pkg/log"
	"github.com/gruntwork-io/terragrunt/pkg/options"
	"golang.org/x/sync/errgroup"
)

// DefaultMaxLevel is the default cap on nested stack-generation levels. A run
// that reaches it is treated as a cycle between stack files. Generous on
// purpose: real stack trees stay far below it.
const DefaultMaxLevel = 1024

// worktreesPerPair is the number of worktrees in a comparison pair: the from worktree and the to worktree.
const worktreesPerPair = 2

// Generator owns the per-working-directory lock for in-process GenerateStacks calls.
type Generator struct {
	locks    *util.KeyLocks
	maxLevel int
}

// NewGenerator returns a ready-to-use Generator.
func NewGenerator() *Generator {
	return &Generator{locks: util.NewKeyLocks(), maxLevel: DefaultMaxLevel}
}

// WithMaxLevel returns the Generator with its nested stack-generation cap set
// to maxLevel, replacing [DefaultMaxLevel]. Tests use it to trip cycle
// detection quickly. Non-positive values are ignored: a cap below one would
// silently skip generation instead of detecting a cycle.
func (g *Generator) WithMaxLevel(maxLevel int) *Generator {
	if maxLevel < 1 {
		return g
	}

	g.maxLevel = maxLevel

	return g
}

// StackNode represents a stack file in the file system.
// The parent is the node that generates the current node,
// and children are the nodes that are generated by the current node.
type StackNode struct {
	Parent   *StackNode
	FilePath string
	Children []*StackNode
	Level    int
}

// NewStackNode creates a new stack node.
func NewStackNode(filePath string) *StackNode {
	return &StackNode{
		FilePath: filePath,
		Level:    -1,
		Children: make([]*StackNode, 0),
	}
}

// stackScope selects which stacks a generation run materializes.
type stackScope int

const (
	// allStacks generates stacks in the working directory and in any provided worktrees.
	allStacks stackScope = iota
	// worktreeStacksOnly generates only the worktree stacks, leaving the working directory untouched.
	worktreeStacksOnly
)

// WorktreeStacks generates the stacks that live inside the comparison worktrees, leaving the
// working directory untouched. It is a no-op when no worktrees are present. find and list use it
// to surface units nested in generated stacks without generating into the user's working directory.
func WorktreeStacks(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wts *worktrees.Worktrees,
) error {
	if wts == nil || len(wts.WorktreePairs) == 0 {
		return nil
	}

	if err := NewGenerator().generateStacks(ctx, l, v, opts, wts, worktreeStacksOnly); err != nil {
		return fmt.Errorf("failed to generate stacks in worktrees: %w", err)
	}

	return nil
}

// GenerateStacks generates every stack file under the working directory, plus any worktree stacks
// carried on wts. Worktrees must be provided by the caller if needed; this function never creates
// worktrees internally.
func (g *Generator) GenerateStacks(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wts *worktrees.Worktrees,
) error {
	return g.generateStacks(ctx, l, v, opts, wts, allStacks)
}

// generateStacks generates the stack files using topological ordering to prevent race conditions.
// Stack files are generated level by level, with parent stacks completing before their children.
// scope selects whether the working directory is included or only the worktree stacks carried on wts.
func (g *Generator) generateStacks(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wts *worktrees.Worktrees,
	scope stackScope,
) error {
	workingDir, err := util.CanonicalResolvedPath(v.FS, opts.WorkingDir, opts.WorkingDir)
	if err != nil {
		return &CanonicalizeWorkingDirError{Path: opts.WorkingDir, Err: err}
	}

	g.locks.Lock(workingDir)
	defer g.locks.Unlock(workingDir)

	foundFiles, err := ListStackFiles(ctx, l, v, opts, wts, scope)
	if err != nil {
		return fmt.Errorf("failed to list stack files in %s %w", opts.WorkingDir, err)
	}

	if len(foundFiles) == 0 {
		if opts.StackAction == "generate" {
			l.Warnf("No stack files found in %s Nothing to generate.", opts.WorkingDir)
		}

		return nil
	}

	// Dedup keyed by canonical stack-file path; accessed only from the main goroutine.
	generatedFiles := make(map[string]bool)

	// Every stack found under a generated stack, keyed by canonical stack-file path.
	foundStacks := make(map[string]component.Component)

	// Tracks which parent stack file first claimed each generated stack, so repeat claims can be warned.
	claimedBy := make(map[string]string)

	stackTrees := BuildStackTopology(l, foundFiles, workingDir)

	maxLevel := g.maxLevel
	for level := range maxLevel {
		if level == maxLevel-1 {
			return fmt.Errorf("cycle detected: maximum level (%d) exceeded", maxLevel)
		}

		levelNodes := getNodesAtLevel(stackTrees, level)
		if len(levelNodes) == 0 {
			break
		}

		warnOnRepeatedClaims(l, levelNodes, claimedBy)

		if err := generateLevel(ctx, l, v, opts, level, levelNodes, generatedFiles); err != nil {
			return err
		}

		err := discoverAndAddNewNodes(
			ctx,
			l,
			v,
			opts,
			wts,
			workingDir,
			levelNodes,
			stackTrees,
			generatedFiles,
			foundStacks,
		)
		if err != nil {
			return err
		}
	}

	// The two sides of a pair can generate the same nested stack at different levels, so matching waits for the last one.
	return recordGeneratedReadingAffected(l, wts, slices.Collect(maps.Values(foundStacks)))
}

// warnOnRepeatedClaims logs a warning when a stack file is claimed by more than
// one parent in the same invocation. All nodes here are stack files by
// construction, since ListStackFiles filters to *component.Stack only.
func warnOnRepeatedClaims(l log.Logger, levelNodes []*StackNode, claimedBy map[string]string) {
	for _, node := range levelNodes {
		parent := "root"
		if node.Parent != nil {
			parent = node.Parent.FilePath
		}

		if prev, seen := claimedBy[node.FilePath]; seen && prev != parent {
			l.Warnf("Stack %q is being generated by %q, but it was already generated by %q. "+
				"You have contention between multiple stacks generating to the same directory. "+
				"This is probably a bug in your stack configurations.",
				node.FilePath, parent, prev)
		}

		claimedBy[node.FilePath] = parent
	}
}

// generateLevel handles the concurrent generation of all stack files at a
// given level. See the "Concurrency invariant" note on generatedFiles in
// GenerateStacks: the map is mutated here from the main goroutine only,
// before any wp.Submit call.
func generateLevel(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	level int,
	levelNodes []*StackNode,
	generatedFiles map[string]bool,
) error {
	l.Debugf("Generating stack level %d with %d files", level, len(levelNodes))

	wp := worker.NewWorkerPool(opts.Parallelism)
	defer wp.Stop()

	for _, node := range levelNodes {
		if generatedFiles[node.FilePath] {
			continue
		}

		generatedFiles[node.FilePath] = true

		// Best-effort skip; GenerateStackFile surfaces ENOENT if the file is removed in the TOCTOU window.
		if !vfs.Exists(v.FS, node.FilePath) {
			continue
		}

		wp.Submit(func() error {
			pctx := configbridge.NewParsingContext(opts)

			scopedLogger, scopedPctx, err := pctx.WithConfigPath(l, node.FilePath)
			if err != nil {
				return err
			}

			return config.GenerateStackFile(ctx, scopedLogger, v, scopedPctx, wp, node.FilePath)
		})
	}

	return wp.Wait()
}

// discoverAndAddNewNodes discovers the stack files generated by levelNodes and
// adds them to the dependency graph. A stack only generates under its own
// directory, into .terragrunt-stack or, with no_dot_terragrunt_stack, beside
// its stack file, so each walk is rooted at the directory of a stack in
// levelNodes instead of re-walking every stack. That stack is found again and
// skipped as an existing node. Every stack a walk finds is kept in foundStacks.
// workingDir must already be canonicalised (cleaned, absolute, symlink-resolved)
// so topology lookups key consistently against the canonicalised foundFiles.
func discoverAndAddNewNodes(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wts *worktrees.Worktrees,
	workingDir string,
	levelNodes []*StackNode,
	dependencyGraph map[string]*StackNode,
	generatedFiles map[string]bool,
	foundStacks map[string]component.Component,
) error {
	var newFiles []string

	for _, node := range levelNodes {
		// A stack file removed in the TOCTOU window was not generated, and its directory may be gone too.
		if !vfs.Exists(v.FS, node.FilePath) {
			continue
		}

		stacks, err := discoverStacksUnder(ctx, l, v, opts, wts, workingDir, filepath.Dir(node.FilePath))
		if err != nil {
			return fmt.Errorf("failed to discover stacks generated by %s: %w", node.FilePath, err)
		}

		for _, c := range stacks {
			if _, ok := c.(*component.Stack); !ok {
				continue
			}

			file, err := util.CanonicalResolvedPath(
				v.FS,
				filepath.Join(c.Path(), config.DefaultStackFile),
				opts.WorkingDir,
			)
			if err != nil {
				return err
			}

			foundStacks[file] = c
			newFiles = append(newFiles, file)
		}
	}

	addNewNodesToGraph(l, dependencyGraph, newFiles, generatedFiles, workingDir)

	return nil
}

// BuildStackTopology creates a topological tree based on directory hierarchy.
func BuildStackTopology(
	l log.Logger,
	stackFiles []string,
	workingDir string,
) map[string]*StackNode {
	nodes := make(map[string]*StackNode)

	for _, file := range stackFiles {
		nodes[file] = NewStackNode(file)
	}

	for _, node := range nodes {
		assignNodeLevel(l, node, nodes, workingDir)
	}

	return nodes
}

// assignNodeLevel recursively assigns levels to nodes based on directory depth.
func assignNodeLevel(
	l log.Logger,
	node *StackNode,
	allNodes map[string]*StackNode,
	workingDir string,
) int {
	if node.Level != -1 {
		return node.Level
	}

	nodeDir := filepath.Dir(node.FilePath)
	parentPath := findParentStackFile(nodeDir, allNodes, workingDir)

	if parentPath == "" {
		node.Level = 0

		return node.Level
	}

	parent := allNodes[parentPath]
	if parent == nil {
		node.Level = 0

		return node.Level
	}

	parentLevel := assignNodeLevel(l, parent, allNodes, workingDir)
	node.Level = parentLevel + 1
	node.Parent = parent
	parent.Children = append(parent.Children, node)

	l.Debugf(
		"Stack %s (level %d) is child of %s (level %d)",
		node.FilePath,
		node.Level,
		parent.FilePath,
		parent.Level,
	)

	return node.Level
}

// findParentStackFile finds the parent stack file for a given directory.
func findParentStackFile(
	childDir string,
	allNodes map[string]*StackNode,
	workingDir string,
) string {
	currentDir := childDir

	for {
		parentDir := filepath.Dir(currentDir)
		if parentDir == currentDir {
			break
		}

		if parentDir == workingDir {
			potentialParent := filepath.Join(workingDir, config.DefaultStackFile)
			if _, exists := allNodes[potentialParent]; exists {
				return potentialParent
			}

			break
		}

		potentialParent := filepath.Join(parentDir, config.DefaultStackFile)
		if _, exists := allNodes[potentialParent]; exists {
			return potentialParent
		}

		currentDir = parentDir
	}

	return ""
}

// getNodesAtLevel returns all nodes at a specific level.
func getNodesAtLevel(nodes map[string]*StackNode, level int) []*StackNode {
	var levelNodes []*StackNode

	for _, node := range nodes {
		if node.Level == level {
			levelNodes = append(levelNodes, node)
		}
	}

	return levelNodes
}

// addNewNodesToGraph adds newly discovered stack files to the dependency graph.
func addNewNodesToGraph(
	l log.Logger,
	existingNodes map[string]*StackNode,
	allFiles []string,
	generatedFiles map[string]bool,
	workingDir string,
) {
	newFiles := make([]string, 0)

	for _, file := range allFiles {
		if _, exists := existingNodes[file]; !exists && !generatedFiles[file] {
			newFiles = append(newFiles, file)
		}
	}

	if len(newFiles) == 0 {
		return
	}

	l.Debugf("Adding %d new stack files to topology graph", len(newFiles))

	for _, file := range newFiles {
		existingNodes[file] = NewStackNode(file)
	}

	for _, file := range newFiles {
		node := existingNodes[file]
		assignNodeLevel(l, node, existingNodes, workingDir)
	}
}

// ListStackFiles returns canonical, symlink-resolved stack-file paths under the absolute opts.WorkingDir.
// For worktreeStacksOnly, stack files in the working directory are skipped and only worktree stacks are returned.
func ListStackFiles(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	worktrees *worktrees.Worktrees,
	scope stackScope,
) ([]string, error) {
	var discoveredComponents component.Components

	stackOpts := discovery.StackGenerateOptions{
		WorkingDir:        opts.WorkingDir,
		DiscoveryBoundary: opts.DiscoveryBoundary,
		Filters:           opts.Filters,
	}

	if scope != worktreeStacksOnly {
		d, err := discovery.NewForStackGenerate(l, v.FS, stackOpts)
		if err != nil {
			return nil, fmt.Errorf("failed to create discovery for stack generate: %w", err)
		}

		discoveredComponents, err = d.Discover(ctx, l, v, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to discover stack files: %w", err)
		}
	}

	worktreeStacks, err := worktreeStacksToGenerate(ctx, l, v, opts, worktrees, stackOpts)
	if err != nil {
		return nil, fmt.Errorf("failed to get worktree stacks to generate: %w", err)
	}

	foundFiles := make([]string, 0, len(discoveredComponents)+len(worktreeStacks))

	foundFiles, err = appendStackFilePaths(v.FS, foundFiles, discoveredComponents, opts.WorkingDir)
	if err != nil {
		return nil, err
	}

	foundFiles, err = appendStackFilePaths(v.FS, foundFiles, worktreeStacks, opts.WorkingDir)
	if err != nil {
		return nil, err
	}

	return foundFiles, nil
}

// ListStackFilesWithExcludes searches for stack files and also returns the set
// of unit paths that should be excluded from the current tofu/terraform command.
// Both results come from a single discovery walk. Stack-file paths and
// excludedPaths keys are canonical symlink-resolved absolute paths; exclusion
// follows [config.ExcludeConfig.Excludes] for opts.TerraformCommand.
func ListStackFilesWithExcludes(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	worktrees *worktrees.Worktrees,
) ([]string, map[string]struct{}, error) {
	stackOpts := discovery.StackGenerateOptions{
		WorkingDir:        opts.WorkingDir,
		DiscoveryBoundary: opts.DiscoveryBoundary,
		Filters:           opts.Filters,
	}

	d, err := discovery.NewForStackGenerate(l, v.FS, stackOpts)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create discovery for stack generate: %w", err)
	}

	d = d.WithParseExclude().WithSuppressParseErrors()

	discoveredComponents, err := d.Discover(ctx, l, v, opts)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to discover stack files: %w", err)
	}

	worktreeStacks, err := worktreeStacksToGenerate(ctx, l, v, opts, worktrees, stackOpts)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to get worktree stacks to generate: %w", err)
	}

	foundFiles, excludedPaths, err := collectStackAndExcludedPaths(
		v.FS,
		discoveredComponents,
		opts.WorkingDir,
	)
	if err != nil {
		return nil, nil, err
	}

	foundFiles, err = appendStackFilePaths(v.FS, foundFiles, worktreeStacks, opts.WorkingDir)
	if err != nil {
		return nil, nil, err
	}

	return foundFiles, excludedPaths, nil
}

// collectStackAndExcludedPaths splits discovered components into canonical stack-file paths and excluded unit paths.
func collectStackAndExcludedPaths(
	fsys vfs.FS,
	components component.Components,
	workingDir string,
) ([]string, map[string]struct{}, error) {
	foundFiles := make([]string, 0, len(components))
	excludedPaths := make(map[string]struct{})

	for _, c := range components {
		switch v := c.(type) {
		case *component.Stack:
			canonical, err := util.CanonicalResolvedPath(
				fsys,
				filepath.Join(c.Path(), config.DefaultStackFile),
				workingDir,
			)
			if err != nil {
				return nil, nil, err
			}

			foundFiles = append(foundFiles, canonical)
		case *component.Unit:
			if !v.Excluded() {
				continue
			}

			canonical, err := util.CanonicalResolvedPath(fsys, v.Path(), workingDir)
			if err != nil {
				return nil, nil, err
			}

			excludedPaths[canonical] = struct{}{}
		}
	}

	return foundFiles, excludedPaths, nil
}

// appendStackFilePaths appends the canonical terragrunt.stack.hcl path of every stack component in
// components to dst, resolving each against workingDir. Non-stack components are skipped.
func appendStackFilePaths(
	fsys vfs.FS,
	dst []string,
	components component.Components,
	workingDir string,
) ([]string, error) {
	for _, c := range components {
		if _, ok := c.(*component.Stack); !ok {
			continue
		}

		canonical, err := util.CanonicalResolvedPath(
			fsys,
			filepath.Join(c.Path(), config.DefaultStackFile),
			workingDir,
		)
		if err != nil {
			return nil, err
		}

		dst = append(dst, canonical)
	}

	return dst, nil
}

// worktreeStacksToGenerate returns a slice of stacks that need to be generated from the worktree stacks.
// When reading filters are present (a stack reads a file that was added, changed, or deleted in the diff),
// it also identifies which stacks are affected and records them on the Worktrees object so that the worktree
// discovery phase can walk them for unit-level changes. A changed or added file is matched against the "to"
// stacks; a deleted file is matched against the "from" stacks, since that is the only side where it still
// exists. The stack walk boundary from stackOpts, mirrored into each worktree, restricts both sets of stacks.
func worktreeStacksToGenerate(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	w *worktrees.Worktrees,
	stackOpts discovery.StackGenerateOptions,
) (component.Components, error) {
	// If worktrees is nil, there are no worktrees to process, return empty components.
	if w == nil {
		return component.Components{}, nil
	}

	boundary := discovery.WorktreeBoundary(ctx, l, v, stackOpts)

	err := discovery.CheckWorktreeBoundaries(ctx, v, w, opts.Filters, opts.DiscoveryBoundary, opts.WorkingDir)
	if err != nil {
		return nil, err
	}

	stacksToGenerate := component.NewThreadSafeComponents(v.FS, component.Components{})

	// If we edit a stack in a worktree, we need to generate it, at the minimum.
	stackDiff := w.Stacks()

	editedStacks := slices.Concat(
		stackDiff.Added,
		stackDiff.Removed,
	)

	for _, changed := range stackDiff.Changed {
		editedStacks = append(editedStacks, changed.FromStack, changed.ToStack)
	}

	for _, stack := range editedStacks {
		if !discovery.WithinWorktreeBoundary(v.FS, stack, boundary) {
			l.Debugf("Skipping stack %s outside the discovery boundary", stack.Path())
			continue
		}

		stacksToGenerate.EnsureComponent(v.FS, stack)
	}

	// When the expanded filter for a given Git expression requires parsing,
	// we need to generate all the stacks in the given worktree, as units within the generated stack might be affected.
	// We also identify which specific stacks are affected by reading filters so that the worktree discovery phase
	// can walk them for unit-level changes.

	g, ctx := errgroup.WithContext(ctx)
	g.SetLimit(min(runtime.GOMAXPROCS(0), max(1, len(w.WorktreePairs)*worktreesPerPair)))

	var (
		mu              sync.Mutex
		errs            []error
		readingAffected []worktrees.StackDiffChangedPair
	)

	// Stacks already covered by a direct change must not be re-recorded, and a stack reading more than one
	// diffed file must be recorded once; both are guarded by this set of stack dirs.
	recordedDirs := make(map[string]struct{}, len(stackDiff.Changed))

	for _, changed := range stackDiff.Changed {
		if dc := changed.ToStack.DiscoveryContext(); dc != nil {
			if rel, err := filepath.Rel(dc.WorkingDir, changed.ToStack.Path()); err == nil {
				recordedDirs[filepath.Clean(rel)] = struct{}{}
			}
		}
	}

	recordReadingAffected := func(fromStack, toStack *component.Stack, rel string) {
		key := filepath.Clean(rel)

		mu.Lock()
		defer mu.Unlock()

		if _, ok := recordedDirs[key]; ok {
			return
		}

		recordedDirs[key] = struct{}{}

		readingAffected = append(readingAffected, worktrees.StackDiffChangedPair{
			FromStack: fromStack,
			ToStack:   toStack,
		})
	}

	for _, pair := range w.WorktreePairs {
		fromFilters, toFilters := pair.FromFilters, pair.ToFilters

		// Evaluate every reading filter, not just the first: a stack matches one filter per file it reads.
		// The from filters mix deleted-file reading filters with path filters for genuine removals, so the
		// partition isolates the reading ones.
		toReadFilters, _ := toFilters.PartitionReadingFilters()
		deletedReadFilters, _ := fromFilters.PartitionReadingFilters()

		if len(toReadFilters) == 0 && len(deletedReadFilters) == 0 {
			continue
		}

		g.Go(func() error {
			recordErr := func(err error) {
				mu.Lock()

				errs = append(errs, err)

				mu.Unlock()
			}

			allFromStacks, err := discoverStacks(
				ctx,
				l,
				v,
				opts,
				pair.FromWorktree,
				len(deletedReadFilters) > 0,
				boundary,
			)
			if err != nil {
				recordErr(err)

				return nil
			}

			allToStacks, err := discoverStacks(
				ctx,
				l,
				v,
				opts,
				pair.ToWorktree,
				len(toReadFilters) > 0,
				boundary,
			)
			if err != nil {
				recordErr(err)

				return nil
			}

			for _, c := range allFromStacks {
				stacksToGenerate.EnsureComponent(v.FS, c)
			}

			for _, c := range allToStacks {
				stacksToGenerate.EnsureComponent(v.FS, c)
			}

			if err := recordReadingAffectedPairs(l, pair, allFromStacks, allToStacks, recordReadingAffected); err != nil {
				recordErr(err)
			}

			return nil
		})
	}

	if err := g.Wait(); err != nil {
		return nil, err
	}

	w.ReadingAffectedStacks = readingAffected

	if len(errs) > 0 {
		return stacksToGenerate.ToComponents(), errors.Join(errs...)
	}

	return stacksToGenerate.ToComponents(), nil
}

// discoverStacksUnder discovers the stacks under the symlink-resolved stackDir. A directory inside a
// comparison worktree is walked like the rest of that worktree, parsing stacks when any pair reading that
// worktree has reading filters for it, since pairs whose expressions share a reference share its worktree.
// Any other directory is walked like the working directory, keeping the user's stack filters and discovery
// boundary. workingDir is opts.WorkingDir with symlinks resolved.
func discoverStacksUnder(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wts *worktrees.Worktrees,
	workingDir string,
	stackDir string,
) (component.Components, error) {
	var (
		wt        *worktrees.Worktree
		readFiles bool
	)

	if wts != nil {
		for _, pair := range wts.WorktreePairs {
			if pair.ToWorktree.Path != "" && vfs.Within(v.FS, pair.ToWorktree.Path, stackDir) {
				toReadFilters, _ := pair.ToFilters.PartitionReadingFilters()

				wt = &pair.ToWorktree
				readFiles = readFiles || len(toReadFilters) > 0
			}

			if pair.FromWorktree.Path != "" && vfs.Within(v.FS, pair.FromWorktree.Path, stackDir) {
				deletedReadFilters, _ := pair.FromFilters.PartitionReadingFilters()

				wt = &pair.FromWorktree
				readFiles = readFiles || len(deletedReadFilters) > 0
			}
		}
	}

	if wt != nil {
		return discoverWorktreeStacksUnder(ctx, l, v, opts, *wt, readFiles, stackDir)
	}

	d, err := discovery.NewForStackGenerate(l, v.FS, discovery.StackGenerateOptions{
		WorkingDir:        opts.WorkingDir,
		DiscoveryBoundary: opts.DiscoveryBoundary,
		Filters:           opts.Filters,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create discovery for stack generate: %w", err)
	}

	// Filters and the discovery boundary match paths spelled like opts.WorkingDir, so the walk root is too.
	walkRoot := stackDir
	if vfs.Within(v.FS, workingDir, stackDir) {
		rel, err := filepath.Rel(workingDir, stackDir)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve %s within %s: %w", stackDir, workingDir, err)
		}

		walkRoot = filepath.Join(opts.WorkingDir, rel)
	}

	return d.WithWalkRoot(walkRoot).Discover(ctx, l, v, opts)
}

// discoverWorktreeStacksUnder discovers the stacks under stackDir, a directory inside the worktree wt.
func discoverWorktreeStacksUnder(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wt worktrees.Worktree,
	readFiles bool,
	stackDir string,
) (component.Components, error) {
	boundary, err := filepath.Rel(wt.Path, stackDir)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve %s within worktree %s: %w", stackDir, wt.Ref, err)
	}

	return discoverStacks(ctx, l, v, opts, wt, readFiles, boundary)
}

// recordGeneratedReadingAffected records the stacks found after generation that read a file diffed by their
// comparison pair, as worktreeStacksToGenerate does for the stacks that exist before generation. A pair that
// is already recorded or changed in the diff is skipped.
func recordGeneratedReadingAffected(l log.Logger, wts *worktrees.Worktrees, stacks component.Components) error {
	if wts == nil {
		return nil
	}

	byWorktree := make(map[string]component.Components, len(stacks))

	for _, c := range stacks {
		dir := c.DiscoveryContext().WorkingDir
		byWorktree[dir] = append(byWorktree[dir], c)
	}

	// Keyed by both stack paths, since pairs whose expressions share a reference reuse the same relative paths.
	type stackPaths struct{ from, to string }

	stackDiff := wts.Stacks()
	recorded := make(map[stackPaths]struct{}, len(stackDiff.Changed)+len(stackDiff.ReadingAffected))

	for _, pairs := range [][]worktrees.StackDiffChangedPair{stackDiff.Changed, stackDiff.ReadingAffected} {
		for _, pair := range pairs {
			recorded[stackPaths{from: pair.FromStack.Path(), to: pair.ToStack.Path()}] = struct{}{}
		}
	}

	record := func(fromStack, toStack *component.Stack, _ string) {
		key := stackPaths{from: fromStack.Path(), to: toStack.Path()}
		if _, ok := recorded[key]; ok {
			return
		}

		recorded[key] = struct{}{}

		wts.ReadingAffectedStacks = append(wts.ReadingAffectedStacks, worktrees.StackDiffChangedPair{
			FromStack: fromStack,
			ToStack:   toStack,
		})
	}

	for _, pair := range wts.WorktreePairs {
		err := recordReadingAffectedPairs(
			l,
			pair,
			byWorktree[pair.FromWorktree.Path],
			byWorktree[pair.ToWorktree.Path],
			record,
		)
		if err != nil {
			return err
		}
	}

	return nil
}

// recordReadingAffectedPairs passes record each stack in toStacks that reads a file changed or added by
// pair, and each stack in fromStacks that reads a file deleted by pair, with the stack at the same path on
// the other side. The stacks must have been discovered with readFiles enabled.
func recordReadingAffectedPairs(
	l log.Logger,
	pair *worktrees.WorktreePair,
	fromStacks component.Components,
	toStacks component.Components,
	record func(fromStack, toStack *component.Stack, rel string),
) error {
	toReadFilters, _ := pair.ToFilters.PartitionReadingFilters()
	deletedReadFilters, _ := pair.FromFilters.PartitionReadingFilters()

	matchedToStacks, err := stacksReadingFiles(l, toReadFilters, toStacks)
	if err != nil {
		return err
	}

	// A stack missing from the "from" side is a fresh addition already covered by stackDiff.Added.
	for _, toStack := range matchedToStacks {
		rel, err := filepath.Rel(pair.ToWorktree.Path, toStack.Path())
		if err != nil {
			continue
		}

		fromStack := findStackByRelPath(fromStacks, pair.FromWorktree.Path, rel)
		if fromStack == nil {
			continue
		}

		record(fromStack, toStack, rel)
	}

	matchedFromStacks, err := stacksReadingFiles(l, deletedReadFilters, fromStacks)
	if err != nil {
		return err
	}

	// A stack missing from the "to" side is a genuine removal already covered by stackDiff.Removed.
	for _, fromStack := range matchedFromStacks {
		rel, err := filepath.Rel(pair.FromWorktree.Path, fromStack.Path())
		if err != nil {
			continue
		}

		toStack := findStackByRelPath(toStacks, pair.ToWorktree.Path, rel)
		if toStack == nil {
			continue
		}

		record(fromStack, toStack, rel)
	}

	return nil
}

// discoverStacks discovers stacks in a worktree.
// When readFiles is true, all discovered stacks are parsed to populate their Reading
// attribute (used by reading-affected detection). A non-empty boundary, relative to
// the worktree root, narrows the walk to that directory.
func discoverStacks(
	ctx context.Context,
	l log.Logger,
	v *venv.Venv,
	opts *options.TerragruntOptions,
	wt worktrees.Worktree,
	readFiles bool,
	boundary string,
) (component.Components, error) {
	d := discovery.NewDiscovery(wt.Path).
		WithSuppressParseErrors().
		WithFilters(StackDiscoveryFilters(opts.Filters))

	if boundary != "" {
		walkRoot, ok, err := discovery.WorktreeWalkRoot(v.FS, wt.Path, boundary)
		if err != nil {
			return nil, fmt.Errorf("failed to discover stacks in worktree %s: %w", wt.Ref, err)
		}

		if !ok {
			return component.Components{}, nil
		}

		d = d.WithWalkRoot(walkRoot)
	}

	if readFiles {
		d = d.WithReadFiles()
	}

	components, err := d.Discover(ctx, l, v, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to discover stacks in worktree %s: %w", wt.Ref, err)
	}

	for _, c := range components {
		dc := c.DiscoveryContext()
		if dc == nil {
			dc = &component.DiscoveryContext{}
		}

		dc.WorkingDir = wt.Path
		dc.Ref = wt.Ref
		c.SetDiscoveryContext(dc)
	}

	return components, nil
}

// findStackByRelPath finds a stack in the given components whose path relative to
// worktreePath matches relPath.
func findStackByRelPath(
	stacks component.Components,
	worktreePath string,
	relPath string,
) *component.Stack {
	for _, c := range stacks {
		s, ok := c.(*component.Stack)
		if !ok {
			continue
		}

		rel, err := filepath.Rel(worktreePath, s.Path())
		if err != nil {
			continue
		}

		if filepath.Clean(rel) == filepath.Clean(relPath) {
			return s
		}
	}

	return nil
}

// stacksReadingFiles returns the stacks among components that read a file targeted by any of the given
// reading filters, deduplicated by path. The components must have been discovered with readFiles enabled
// so their Reading attribute is populated.
func stacksReadingFiles(
	l log.Logger,
	readingFilters filter.Filters,
	components component.Components,
) ([]*component.Stack, error) {
	seen := make(map[string]struct{})
	matched := make([]*component.Stack, 0, len(readingFilters))

	for _, f := range readingFilters {
		evaluated, err := filter.Evaluate(l, filter.EvaluationContext{}, f.Expression(), components)
		if err != nil {
			return nil, err
		}

		for _, c := range evaluated {
			stack, ok := c.(*component.Stack)
			if !ok {
				continue
			}

			if _, ok := seen[stack.Path()]; ok {
				continue
			}

			seen[stack.Path()] = struct{}{}
			matched = append(matched, stack)
		}
	}

	return matched, nil
}

// StackDiscoveryFilters returns the filters that select which stacks a generation run
// discovers, so that explicit exclusions like --filter '!./land-mine | type=stack' are
// respected.
//
// Generation stays permissive until the user aims a filter at stacks, because a stack can
// generate its units anywhere, so narrowing by a filter that never mentions stacks would drop
// stacks the user still needs. Once a stack-targeted filter is present, every other filter is
// narrowed to the stacks it matches and joins the union, rather than being dropped, which
// would lose the stacks only that filter selects. Filters union, so a blanket type=stack
// alongside them would select every stack and undo the exclusions.
//
// Git expressions are left out: they match on a component's Git reference, which discovery
// only stamps on afterwards, so folding them in here would select nothing.
func StackDiscoveryFilters(filters filter.Filters) filter.Filters {
	stackFilters := filters.RestrictToStacks()
	if len(stackFilters) == 0 {
		return stackTypeFilter()
	}

	result := make(filter.Filters, 0, len(filters))
	result = append(result, stackFilters...)

	for _, f := range filters.ExcludingGitFilters() {
		expr := f.Expression()
		if expr.IsRestrictedToStacks() {
			continue
		}

		// A filter that only excludes already subtracts from the union, so narrowing it to
		// stacks would turn it into a selector and hand back what it set out to remove.
		if filter.IsPureNegation(expr) {
			result = append(result, f)

			continue
		}

		attrExpr := filter.NewTypeExpression(component.StackKind)
		result = append(result, filter.NewFilter(
			filter.NewInfixExpression(expr, "|", attrExpr),
			f.String(),
		))
	}

	return result
}

// stackTypeFilter returns a filter.Filters that restricts to stack components.
func stackTypeFilter() filter.Filters {
	attrExpr := filter.NewTypeExpression(component.StackKind)

	return filter.Filters{filter.NewFilter(attrExpr, attrExpr.String())}
}
