// Code generated by MockGen. DO NOT EDIT.
// Source: lock.go
//
// Generated by this command:
//
//	mockgen -source=lock.go -destination=mocks/mock_lock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
