# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-test-bucket-ztu5vh"
    dynamodb_table = "terragrunt-test-locks-zhlyyv"
    encrypt        = true
    key            = "terraform.tfstate"
    region         = "us-west-2"
  }
}
