package config

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/hcl/v2/hclsyntax"

	"github.com/gruntwork-io/terragrunt/util"
	"github.com/hashicorp/hcl/v2/hclwrite"

	"github.com/zclconf/go-cty/cty"

	"github.com/gruntwork-io/terragrunt/config/hclparse"
	"github.com/gruntwork-io/terragrunt/internal/errors"
	"github.com/gruntwork-io/terragrunt/options"
)

const (
	stackDir       = ".terragrunt-stack"
	unitValuesFile = "terragrunt.values.hcl"
	unitDirPerm    = 0755
	valueFilePerm  = 0644
)

// StackConfigFile represents the structure of terragrunt.stack.hcl stack file.
type StackConfigFile struct {
	Locals *terragruntLocal `hcl:"locals,block"`
	Stacks []*Stack         `hcl:"stack,block"`
	Units  []*Unit          `hcl:"unit,block"`
}

// Unit represent unit from stack file.
type Unit struct {
	Name   string     `hcl:",label"`
	Source string     `hcl:"source,attr"`
	Path   string     `hcl:"path,attr"`
	Values *cty.Value `hcl:"values,attr"`
}

// Stack represents the stack block in the configuration.
type Stack struct {
	Name   string `hcl:",label"`
	Source string `hcl:"source,attr"`
	Path   string `hcl:"path,attr"`
}

// ReadOutputs reads the outputs from the unit.
func (u *Unit) ReadOutputs(ctx context.Context, opts *options.TerragruntOptions, unitDir string) (map[string]cty.Value, error) {
	configPath := filepath.Join(unitDir, DefaultTerragruntConfigPath)
	opts.Logger.Debugf("Getting output from unit %s in %s", u.Name, unitDir)

	parserCtx := NewParsingContext(ctx, opts)

	jsonBytes, err := getOutputJSONWithCaching(parserCtx, configPath) //nolint: contextcheck

	if err != nil {
		return nil, errors.New(err)
	}

	outputMap, err := TerraformOutputJSONToCtyValueMap(configPath, jsonBytes)

	if err != nil {
		return nil, errors.New(err)
	}

	return outputMap, nil
}

// ReadStackConfigFile reads the terragrunt.stack.hcl file.
func ReadStackConfigFile(ctx context.Context, opts *options.TerragruntOptions, filePath string) (*StackConfigFile, error) {
	opts.Logger.Debugf("Reading Terragrunt stack config file at %s", filePath)

	parser := NewParsingContext(ctx, opts)

	file, err := hclparse.NewParser(parser.ParserOptions...).ParseFromFile(filePath)
	if err != nil {
		return nil, errors.New(err)
	}
	//nolint:contextcheck
	if err := processLocals(parser, opts, file); err != nil {
		return nil, errors.New(err)
	}
	//nolint:contextcheck
	evalParsingContext, err := createTerragruntEvalContext(parser, file.ConfigPath)
	if err != nil {
		return nil, errors.New(err)
	}

	config := &StackConfigFile{}
	if err := file.Decode(config, evalParsingContext); err != nil {
		return nil, errors.New(err)
	}

	if err := ValidateStackConfig(config); err != nil {
		return nil, errors.New(err)
	}

	return config, nil
}

// WriteUnitValues generates and writes unit values to a terragrunt.values.hcl file in the specified unit directory.
// If the unit has no values (Values is nil), the function logs a debug message and returns.
// Parameters:
//   - opts: TerragruntOptions containing logger and other configuration
//   - unit: Unit containing the values to write
//   - unitDirectory: Target directory where the values file will be created
//
// Returns an error if the directory creation or file writing fails.
func WriteUnitValues(opts *options.TerragruntOptions, unit *Unit, unitDirectory string) error {
	if unitDirectory == "" {
		return errors.New("WriteUnitValues: unit directory path cannot be empty")
	}

	if err := os.MkdirAll(unitDirectory, unitDirPerm); err != nil {
		return errors.Errorf("failed to create directory %s: %w", unitDirectory, err)
	}

	filePath := filepath.Join(unitDirectory, unitValuesFile)
	if unit.Values == nil {
		opts.Logger.Debugf("No values to write for unit %s in %s", unit.Name, filePath)
		return nil
	}

	opts.Logger.Debugf("Writing values for unit %s in %s", unit.Name, filePath)

	file := hclwrite.NewEmptyFile()
	body := file.Body()
	body.AppendUnstructuredTokens([]*hclwrite.Token{
		{
			Type:  hclsyntax.TokenComment,
			Bytes: []byte("# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually\n"),
		},
	})

	for key, val := range unit.Values.AsValueMap() {
		body.SetAttributeValue(key, val)
	}

	if err := os.WriteFile(filePath, file.Bytes(), valueFilePerm); err != nil {
		return errors.Errorf("failed to write values file %s: %w", filePath, err)
	}

	return nil
}

// ReadUnitValues reads the unit values from the terragrunt.values.hcl file.
func ReadUnitValues(ctx context.Context, opts *options.TerragruntOptions, unitDirectory string) (*cty.Value, error) {
	if unitDirectory == "" {
		return nil, errors.New("ReadUnitValues: unit directory path cannot be empty")
	}

	filePath := filepath.Join(unitDirectory, unitValuesFile)

	if util.FileNotExists(filePath) {
		return nil, nil
	}

	opts.Logger.Debugf("Reading Terragrunt stack values file at %s", filePath)
	parser := NewParsingContext(ctx, opts)
	file, err := hclparse.NewParser(parser.ParserOptions...).ParseFromFile(filePath)

	if err != nil {
		return nil, errors.New(err)
	}
	//nolint:contextcheck
	evalParsingContext, err := createTerragruntEvalContext(parser, file.ConfigPath)

	if err != nil {
		return nil, errors.New(err)
	}

	values := map[string]cty.Value{}

	if err := file.Decode(&values, evalParsingContext); err != nil {
		return nil, errors.New(err)
	}

	result := cty.ObjectVal(values)

	return &result, nil
}

// ValidateStackConfig validates a StackConfigFile instance according to the rules:
// - Unit name, source, and path shouldn't be empty
// - Unit names should be unique
// - Units shouldn't have duplicate paths
// - Stack name, source, and path shouldn't be empty
// - Stack names should be unique
// - Stack shouldn't have duplicate paths
func ValidateStackConfig(config *StackConfigFile) error {
	if config == nil {
		return errors.New("stack config cannot be nil")
	}

	// Check if we have any units or stacks
	if len(config.Units) == 0 && len(config.Stacks) == 0 {
		return errors.New("stack config must contain at least one unit or stack")
	}

	validationErrors := &errors.MultiError{}
	if err := validateUnits(config.Units); err != nil {
		validationErrors.Append(err)
	}
	if err := validateStacks(config.Stacks); err != nil {
		validationErrors.Append(err)
	}
	return validationErrors.ErrorOrNil()
}

// validateUnits validates all units in the configuration
func validateUnits(units []*Unit) error {
	if len(units) == 0 {
		return nil
	}
	validationErrors := &errors.MultiError{}
	// Pre-allocate maps with known capacity to avoid resizing
	names := make(map[string]bool, len(units))
	paths := make(map[string]bool, len(units))

	for i, unit := range units {
		if unit == nil {
			validationErrors.Append(errors.Errorf("unit at index %d is nil", i))
			continue
		}

		name := strings.TrimSpace(unit.Name)
		path := strings.TrimSpace(unit.Path)
		source := strings.TrimSpace(unit.Source)

		// Validate name
		if name == "" {
			validationErrors.Append(errors.Errorf("unit at index %d has empty name", i))
		}

		// Validate source
		if source == "" {
			validationErrors.Append(errors.Errorf("unit '%s' has empty source", unit.Name))
		}

		// Validate path
		if path == "" {
			validationErrors.Append(errors.Errorf("unit '%s' has empty path", unit.Name))
		}

		// Check for duplicates
		if names[name] {
			validationErrors.Append(errors.Errorf("duplicate unit name found: '%s'", unit.Name))
		}

		if paths[path] {
			validationErrors.Append(errors.Errorf("duplicate unit path found: '%s'", unit.Path))
		}

		// Save non-empty values for uniqueness check
		if name != "" {
			names[name] = true
		}

		if path != "" {
			paths[path] = true
		}
	}
	return validationErrors.ErrorOrNil()
}

// validateStacks validates all stacks in the configuration
func validateStacks(stacks []*Stack) error {
	if len(stacks) == 0 {
		return nil
	}
	validationErrors := &errors.MultiError{}
	// Pre-allocate maps with known capacity to avoid resizing
	names := make(map[string]bool, len(stacks))
	paths := make(map[string]bool, len(stacks))

	for i, stack := range stacks {
		if stack == nil {
			validationErrors.Append(errors.Errorf("stack at index %d is nil", i))
			continue
		}

		name := strings.TrimSpace(stack.Name)
		path := strings.TrimSpace(stack.Path)
		source := strings.TrimSpace(stack.Source)

		// Validate name
		if name == "" {
			validationErrors.Append(errors.Errorf("stack at index %d has empty name", i))
		}

		// Validate source
		if source == "" {
			validationErrors.Append(errors.Errorf("stack '%s' has empty source", stack.Name))
		}

		// Validate path
		if path == "" {
			validationErrors.Append(errors.Errorf("stack '%s' has empty path", stack.Name))
		}

		// Check for duplicates
		if names[name] {
			validationErrors.Append(errors.Errorf("duplicate stack name found: '%s'", stack.Name))
		}

		if paths[path] {
			validationErrors.Append(errors.Errorf("duplicate stack path found: '%s'", stack.Path))
		}

		// Save non-empty values for uniqueness check
		if name != "" {
			names[name] = true
		}

		if path != "" {
			paths[path] = true
		}
	}
	return validationErrors.ErrorOrNil()
}

func processLocals(parser *ParsingContext, opts *options.TerragruntOptions, file *hclparse.File) error {
	localsBlock, err := file.Blocks(MetadataLocals, false)

	if err != nil {
		return errors.New(err)
	}

	if len(localsBlock) == 0 {
		return nil
	}

	if len(localsBlock) > 1 {
		return errors.New(fmt.Sprintf("up to one locals block is allowed per stack file, but found %d in %s", len(localsBlock), file.ConfigPath))
	}

	attrs, err := localsBlock[0].JustAttributes()

	if err != nil {
		return errors.New(err)
	}

	evaluatedLocals := map[string]cty.Value{}
	evaluated := true

	for iterations := 0; len(attrs) > 0 && evaluated; iterations++ {
		if iterations > MaxIter {
			// Reached maximum supported iterations, which is most likely an infinite loop bug so cut the iteration
			// short and return an error.
			return errors.New(MaxIterError{})
		}

		var err error
		attrs, evaluatedLocals, evaluated, err = attemptEvaluateLocals(
			parser,
			file,
			attrs,
			evaluatedLocals,
		)

		if err != nil {
			opts.Logger.Debugf("Encountered error while evaluating locals in file %s", opts.TerragruntStackConfigPath)

			return errors.New(err)
		}
	}

	localsAsCtyVal, err := convertValuesMapToCtyVal(evaluatedLocals)

	if err != nil {
		return errors.New(err)
	}

	parser.Locals = &localsAsCtyVal

	return nil
}
