package component_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gruntwork-io/terragrunt/internal/services/catalog/component"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/test/helpers"
)

const (
	testSrcDir = "/repo/vpc"
	testDstDir = "/work"
)

func TestScaffoldCopiesIntoDestination(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# vpc unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "inputs.hcl"), "# inputs\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, ".terragrunt-cache", "junk.txt"), "skipped")

	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	result, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)
	require.NoError(t, err)
	assert.Equal(t, testDstDir, result.Dir)

	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "inputs.hcl"))
	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, ".terragrunt-cache", "junk.txt"))
	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, ".terragrunt-cache"))
}

func TestScaffoldWritesValuesStub(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), `
locals {
  region = values.region
}

inputs = {
  app = values.app
  env = values.env
}
`)

	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	result, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)
	require.NoError(t, err)
	assert.True(t, result.ValuesWritten)
	assert.False(t, result.ValuesSkipped)
	assert.Equal(t, []string{"app", "env", "region"}, result.References.Required)

	valuesPath := filepath.Join(testDstDir, "terragrunt.values.hcl")
	assertFileExistsFS(t, fsys, valuesPath)

	raw, err := vfs.ReadFile(fsys, valuesPath)
	require.NoError(t, err)

	content := string(raw)
	assert.Contains(t, content, "# Auto-generated by Terragrunt")

	appIdx := strings.Index(content, "\napp")

	envIdx := strings.Index(content, "\nenv")

	regionIdx := strings.Index(content, "\nregion")

	require.NotEqual(t, -1, appIdx)
	require.NotEqual(t, -1, envIdx)
	require.NotEqual(t, -1, regionIdx)
	assert.Less(t, appIdx, envIdx)
	assert.Less(t, envIdx, regionIdx)
}

func TestScaffoldWritesSuppliedValues(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)
	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	_, err := component.Scaffold(
		fsys, component.KindUnit, testSrcDir, testDstDir,
		map[string]string{"region": `"us-east-1"`},
	)
	require.NoError(t, err)

	raw, err := vfs.ReadFile(fsys, filepath.Join(testDstDir, "terragrunt.values.hcl"))
	require.NoError(t, err)
	assert.Contains(t, string(raw), `region = "us-east-1"`)
}

func TestScaffoldLeavesExistingValuesFileAlone(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)

	existing := []byte(`region = "us-east-1"` + "\n")
	valuesPath := filepath.Join(testDstDir, "terragrunt.values.hcl")
	require.NoError(t, vfs.WriteFile(fsys, valuesPath, existing, 0o644))

	result, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)
	require.NoError(t, err)
	assert.False(t, result.ValuesWritten)
	assert.True(t, result.ValuesSkipped)

	got, err := vfs.ReadFile(fsys, valuesPath)
	require.NoError(t, err)
	assert.Equal(t, existing, got, "pre-existing values file should be untouched")
}

func TestScaffoldRefusesToOverwriteExistingFile(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.stack.hcl"), "# stack\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "terragrunt.stack.hcl"), "# preexisting")

	_, err := component.Scaffold(fsys, component.KindStack, testSrcDir, testDstDir, nil)

	var destErr *component.DestinationExistsError

	require.ErrorAs(t, err, &destErr)
	assert.Equal(t, filepath.Join(testDstDir, "terragrunt.stack.hcl"), destErr.Path)
}

// TestScaffoldLeavesDestinationUntouchedOnCollision pins the all-or-nothing
// promise: a collision on any file must abort before the others are written.
func TestScaffoldLeavesDestinationUntouchedOnCollision(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "inputs.hcl"), "# inputs\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "inputs.hcl"), "# preexisting")

	_, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)
	require.Error(t, err)

	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
}

func TestScaffoldRejectsNonCopyableKind(t *testing.T) {
	t.Parallel()

	for _, kind := range []component.Kind{component.KindModule, component.KindTemplate} {
		t.Run(kind.String(), func(t *testing.T) {
			t.Parallel()

			fsys := vfs.NewMemMapFS()
			writeFileFS(t, fsys, filepath.Join(testSrcDir, "main.tf"), "# module\n")

			_, err := component.Scaffold(fsys, kind, testSrcDir, testDstDir, nil)
			require.ErrorIs(t, err, component.ErrNotCopyable)

			assertNotExistsFS(t, fsys, filepath.Join(testDstDir, "main.tf"))
		})
	}
}

func TestScaffoldFailsWhenSourceMissing(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()
	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	_, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)
	require.Error(t, err)
}

func TestScaffoldRejectsValuesStubWhenPathIsDirectory(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)
	require.NoError(t, fsys.MkdirAll(filepath.Join(testDstDir, "terragrunt.values.hcl"), 0o755))

	_, err := component.Scaffold(fsys, component.KindUnit, testSrcDir, testDstDir, nil)

	var notRegularErr *component.DestinationNotRegularError

	require.ErrorAs(t, err, &notRegularErr)
	assert.Equal(t, filepath.Join(testDstDir, "terragrunt.values.hcl"), notRegularErr.Path)
}

// TestScaffoldSkipsSymlinks stays on the real OS filesystem because the
// behavior under test is symlink-skipping, and only OsFs participates in the
// symlink semantics that os.Symlink + lstat exercise.
func TestScaffoldSkipsSymlinks(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewOSFS()
	srcDir := filepath.Join(helpers.TmpDirWOSymlinks(t), "vpc")

	writeFileFS(t, fsys, filepath.Join(srcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(srcDir, "real.txt"), "hello\n")
	require.NoError(t, os.Symlink("real.txt", filepath.Join(srcDir, "link.txt")))

	dstDir := t.TempDir()

	_, err := component.Scaffold(fsys, component.KindUnit, srcDir, dstDir, nil)
	require.NoError(t, err)

	assert.FileExists(t, filepath.Join(dstDir, "real.txt"))
	assert.NoFileExists(t, filepath.Join(dstDir, "link.txt"))
}

func writeFileFS(t *testing.T, fsys vfs.FS, path, contents string) {
	t.Helper()

	require.NoError(t, fsys.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, vfs.WriteFile(fsys, path, []byte(contents), 0o644))
}

func assertFileExistsFS(t *testing.T, fsys vfs.FS, path string) {
	t.Helper()

	exists, err := vfs.FileExists(fsys, path)
	require.NoError(t, err)
	assert.True(t, exists, "expected %q to exist on fsys", path)
}

func assertNotExistsFS(t *testing.T, fsys vfs.FS, path string) {
	t.Helper()

	exists, err := vfs.FileExists(fsys, path)
	require.NoError(t, err)
	assert.False(t, exists, "expected %q to not exist on fsys", path)
}
