package component_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/gruntwork-io/terragrunt/internal/services/catalog/component"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/test/helpers"
)

const (
	testRootDir = "/repo"
	testSrcDir  = "/repo/vpc"
	testDstDir  = "/work"
)

func TestScaffoldCopiesIntoDestination(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# vpc unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "inputs.hcl"), "# inputs\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, ".terragrunt-cache", "junk.txt"), "skipped")

	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	result, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.NoError(t, err)
	assert.Equal(t, testDstDir, result.Dir)

	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "inputs.hcl"))
	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, ".terragrunt-cache", "junk.txt"))
	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, ".terragrunt-cache"))
}

func TestScaffoldWritesValuesStub(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), `
locals {
  region = values.region
}

inputs = {
  app = values.app
  env = values.env
}
`)

	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	result, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.NoError(t, err)
	assert.True(t, result.ValuesWritten)
	assert.False(t, result.ValuesSkipped)
	assert.Equal(t, []string{"app", "env", "region"}, result.References.Required)

	valuesPath := filepath.Join(testDstDir, "terragrunt.values.hcl")
	assertFileExistsFS(t, fsys, valuesPath)

	raw, err := vfs.ReadFile(fsys, valuesPath)
	require.NoError(t, err)

	content := string(raw)
	assert.Contains(t, content, "# Auto-generated by Terragrunt")

	appIdx := strings.Index(content, "\napp")

	envIdx := strings.Index(content, "\nenv")

	regionIdx := strings.Index(content, "\nregion")

	require.NotEqual(t, -1, appIdx)
	require.NotEqual(t, -1, envIdx)
	require.NotEqual(t, -1, regionIdx)
	assert.Less(t, appIdx, envIdx)
	assert.Less(t, envIdx, regionIdx)
}

func TestScaffoldWritesSuppliedValues(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)
	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir},
		map[string]string{"region": `"us-east-1"`},
	)
	require.NoError(t, err)

	raw, err := vfs.ReadFile(fsys, filepath.Join(testDstDir, "terragrunt.values.hcl"))
	require.NoError(t, err)
	assert.Contains(t, string(raw), `region = "us-east-1"`)
}

func TestScaffoldLeavesExistingValuesFileAlone(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)

	existing := []byte(`region = "us-east-1"` + "\n")
	valuesPath := filepath.Join(testDstDir, "terragrunt.values.hcl")
	require.NoError(t, vfs.WriteFile(fsys, valuesPath, existing, 0o644))

	result, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.NoError(t, err)
	assert.False(t, result.ValuesWritten)
	assert.True(t, result.ValuesSkipped)

	got, err := vfs.ReadFile(fsys, valuesPath)
	require.NoError(t, err)
	assert.Equal(t, existing, got, "pre-existing values file should be untouched")
}

func TestScaffoldRefusesToOverwriteExistingFile(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.stack.hcl"), "# stack\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "terragrunt.stack.hcl"), "# preexisting")

	_, err := component.Scaffold(fsys, component.KindStack, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)

	var destErr *component.DestinationExistsError

	require.ErrorAs(t, err, &destErr)
	assert.Equal(t, filepath.Join(testDstDir, "terragrunt.stack.hcl"), destErr.Path)
}

// TestScaffoldLeavesDestinationUntouchedOnCollision pins the all-or-nothing
// promise: a collision on any file must abort before the others are written.
func TestScaffoldLeavesDestinationUntouchedOnCollision(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "inputs.hcl"), "# inputs\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "inputs.hcl"), "# preexisting")

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.Error(t, err)

	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
}

func TestScaffoldRefusesToCopyIntoNonDirectory(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "scripts", "run.sh"), "#!/bin/sh\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "scripts"), "# preexisting")

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)

	var notDirErr *component.DestinationNotDirectoryError

	require.ErrorAs(t, err, &notDirErr)
	assert.Equal(t, filepath.Join(testDstDir, "scripts"), notDirErr.Path)

	// Nothing may be written before the collision is found.
	assertNotExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
}

// TestScaffoldCopiesIntoExistingDirectory pins that a component directory may
// merge into an existing one; only a file on an occupied path is a collision.
func TestScaffoldCopiesIntoExistingDirectory(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(testSrcDir, "scripts", "run.sh"), "#!/bin/sh\n")
	writeFileFS(t, fsys, filepath.Join(testDstDir, "scripts", "keep.sh"), "# mine\n")

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.NoError(t, err)

	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "terragrunt.hcl"))
	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "scripts", "run.sh"))
	assertFileExistsFS(t, fsys, filepath.Join(testDstDir, "scripts", "keep.sh"))
}

func TestScaffoldRejectsNonCopyableKind(t *testing.T) {
	t.Parallel()

	for _, kind := range []component.Kind{component.KindModule, component.KindTemplate} {
		t.Run(kind.String(), func(t *testing.T) {
			t.Parallel()

			fsys := vfs.NewMemMapFS()
			writeFileFS(t, fsys, filepath.Join(testSrcDir, "main.tf"), "# module\n")

			_, err := component.Scaffold(fsys, kind, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
			require.ErrorIs(t, err, component.ErrNotCopyable)

			assertNotExistsFS(t, fsys, filepath.Join(testDstDir, "main.tf"))
		})
	}
}

func TestScaffoldFailsWhenSourceMissing(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()
	require.NoError(t, fsys.MkdirAll(testDstDir, 0o755))

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)
	require.Error(t, err)
}

func TestScaffoldRejectsValuesStubWhenPathIsDirectory(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewMemMapFS()

	writeFileFS(t, fsys, filepath.Join(testSrcDir, "terragrunt.hcl"),
		`locals { region = values.region }`)
	require.NoError(t, fsys.MkdirAll(filepath.Join(testDstDir, "terragrunt.values.hcl"), 0o755))

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: testRootDir, Src: testSrcDir, Dst: testDstDir}, nil)

	var notRegularErr *component.DestinationNotRegularError

	require.ErrorAs(t, err, &notRegularErr)
	assert.Equal(t, filepath.Join(testDstDir, "terragrunt.values.hcl"), notRegularErr.Path)
}

// TestScaffoldReproducesSymlinksWithinComponent stays on the real OS
// filesystem because the behavior under test is symlink handling, and only
// OsFs participates in the symlink semantics that os.Symlink + lstat exercise.
func TestScaffoldReproducesSymlinksWithinComponent(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewOSFS()
	srcRoot := helpers.TmpDirWOSymlinks(t)
	srcDir := filepath.Join(srcRoot, "vpc")

	writeFileFS(t, fsys, filepath.Join(srcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(srcDir, "real.txt"), "hello\n")
	require.NoError(t, os.Symlink("real.txt", filepath.Join(srcDir, "link.txt")))

	dstDir := t.TempDir()

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: srcRoot, Src: srcDir, Dst: dstDir}, nil)
	require.NoError(t, err)

	assert.FileExists(t, filepath.Join(dstDir, "real.txt"))

	linkPath := filepath.Join(dstDir, "link.txt")

	target, err := os.Readlink(linkPath)
	require.NoError(t, err, "the link must be reproduced as a link, not dereferenced")
	assert.Equal(t, "real.txt", target)

	// real.txt was copied too, so the link resolves.
	contents, err := os.ReadFile(linkPath)
	require.NoError(t, err)
	assert.Equal(t, "hello\n", string(contents))
}

// TestScaffoldReproducesSymlinkedRootConfig pins that a component whose root
// configuration is a symlink lands with that configuration present. Dropping
// it would report success having scaffolded a unit with nothing to run.
func TestScaffoldReproducesSymlinkedRootConfig(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewOSFS()
	srcRoot := helpers.TmpDirWOSymlinks(t)
	srcDir := filepath.Join(srcRoot, "vpc")

	writeFileFS(t, fsys, filepath.Join(srcRoot, "shared", "terragrunt.hcl"),
		"locals { region = values.region }")
	require.NoError(t, fsys.MkdirAll(srcDir, 0o755))
	require.NoError(t, os.Symlink(
		filepath.Join("..", "shared", "terragrunt.hcl"),
		filepath.Join(srcDir, "terragrunt.hcl"),
	))

	markers, err := component.Inspect(fsys, srcDir)
	require.NoError(t, err)

	kind, ok := markers.CopyKind()
	require.True(t, ok, "a symlinked terragrunt.hcl still marks a unit")
	require.Equal(t, component.KindUnit, kind)

	dstDir := t.TempDir()

	result, err := component.Scaffold(fsys, kind, component.Paths{Root: srcRoot, Src: srcDir, Dst: dstDir}, nil)
	require.NoError(t, err)

	contents, err := os.ReadFile(filepath.Join(dstDir, "terragrunt.hcl"))
	require.NoError(t, err)
	assert.Equal(t, "locals { region = values.region }", string(contents))

	// The references behind the link are still collected.
	assert.Equal(t, []string{"region"}, result.References.Required)
	assert.True(t, result.ValuesWritten)
}

// TestScaffoldReproducesDirectorySymlinks pins that a link to a directory
// inside the component is reproduced as a link rather than walked into and
// copied twice.
func TestScaffoldReproducesDirectorySymlinks(t *testing.T) {
	t.Parallel()

	fsys := vfs.NewOSFS()
	srcRoot := helpers.TmpDirWOSymlinks(t)
	srcDir := filepath.Join(srcRoot, "vpc")

	writeFileFS(t, fsys, filepath.Join(srcDir, "terragrunt.hcl"), "# unit\n")
	writeFileFS(t, fsys, filepath.Join(srcDir, "scripts", "run.sh"), "#!/bin/sh\n")
	require.NoError(t, os.Symlink("scripts", filepath.Join(srcDir, "bin")))

	dstDir := t.TempDir()

	_, err := component.Scaffold(fsys, component.KindUnit, component.Paths{Root: srcRoot, Src: srcDir, Dst: dstDir}, nil)
	require.NoError(t, err)

	target, err := os.Readlink(filepath.Join(dstDir, "bin"))
	require.NoError(t, err)
	assert.Equal(t, "scripts", target)

	assert.FileExists(t, filepath.Join(dstDir, "scripts", "run.sh"))
	assert.FileExists(t, filepath.Join(dstDir, "bin", "run.sh"))
}

func writeFileFS(t *testing.T, fsys vfs.FS, path, contents string) {
	t.Helper()

	require.NoError(t, fsys.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, vfs.WriteFile(fsys, path, []byte(contents), 0o644))
}

func assertFileExistsFS(t *testing.T, fsys vfs.FS, path string) {
	t.Helper()

	exists, err := vfs.FileExists(fsys, path)
	require.NoError(t, err)
	assert.True(t, exists, "expected %q to exist on fsys", path)
}

func assertNotExistsFS(t *testing.T, fsys vfs.FS, path string) {
	t.Helper()

	exists, err := vfs.FileExists(fsys, path)
	require.NoError(t, err)
	assert.False(t, exists, "expected %q to not exist on fsys", path)
}
