# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "swift" {
    archive_container = "terraform_state-archive"
    cloud             = "dummy"
    container         = "terraform_state"
    region_name       = "dummy"
    state_name        = "dummy"
    tenant_name       = "dummy"
    user_id           = "dummy"
    user_name         = "dummy"
  }
}
