package hclparse

import (
	"path/filepath"
	"slices"

	"github.com/gruntwork-io/terragrunt/internal/errors"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

const (
	// AutoIncludeFile is the filename for generated autoinclude files.
	AutoIncludeFile = "terragrunt.autoinclude.hcl"
	// autoIncludeFilePerm is the file permission for generated autoinclude files.
	autoIncludeFilePerm = 0644
	// autoIncludeDirPerm is the directory permission for generated autoinclude dirs.
	autoIncludeDirPerm = 0755
)

// GenerateAutoIncludeFile writes a terragrunt.autoinclude.hcl file in the
// given directory from a resolved autoinclude.
//
// The generated file contains:
//   - dependency blocks with resolved config_path and all other attributes
//     (mock_outputs, mock_outputs_allowed_terraform_commands, etc.) copied
//     from the original AST source bytes.
//   - All non-dependency content (inputs, retry blocks, etc.) copied verbatim
//     from the original AST source bytes — dependency.*.outputs.* references
//     are preserved without evaluation.
//
// srcBytes is the original terragrunt.stack.hcl file content, used to extract
// source text for expressions via byte ranges.
func GenerateAutoIncludeFile(fs vfs.FS, resolved *AutoIncludeResolved, targetDir string, srcBytes []byte, evalCtx *hcl.EvalContext) error {
	if resolved == nil {
		return nil
	}

	body, ok := resolved.RawBody.(*hclsyntax.Body)
	if !ok {
		return errors.New("autoinclude raw body is not *hclsyntax.Body")
	}

	out := hclwrite.NewEmptyFile()
	outBody := out.Body()

	outBody.AppendUnstructuredTokens(CommentTokens("# Generated by Terragrunt from autoinclude block. Do not edit manually.\n"))

	// Write dependency blocks with resolved config_path.
	for _, dep := range resolved.Dependencies {
		origBlock := FindBlock(body, blockDependency, dep.Name)
		if origBlock == nil {
			continue
		}

		writeDependencyBlock(outBody, dep, origBlock, srcBytes, targetDir)
		outBody.AppendNewline()
	}

	// Write non-dependency content with binary per-attribute evaluation.
	writeNonDependencyContent(outBody, body, srcBytes, evalCtx)

	filePath := filepath.Join(targetDir, AutoIncludeFile)

	if err := fs.MkdirAll(targetDir, autoIncludeDirPerm); err != nil {
		return errors.Errorf("failed to create directory %s: %w", targetDir, err)
	}

	formatted := hclwrite.Format(out.Bytes())

	if err := vfs.WriteFile(fs, filePath, formatted, autoIncludeFilePerm); err != nil {
		return errors.Errorf("failed to write %s: %w", filePath, err)
	}

	return nil
}

// writeDependencyBlock writes a single dependency block with resolved config_path.
// The config_path is converted to a path relative to targetDir. All other
// attributes are copied from source bytes to preserve original expressions.
func writeDependencyBlock(outBody *hclwrite.Body, dep AutoIncludeDependency, origBlock *hclsyntax.Block, srcBytes []byte, targetDir string) {
	depBlock := outBody.AppendNewBlock(blockDependency, []string{dep.Name})
	depBody := depBlock.Body()

	// Convert config_path to relative from the target directory.
	relPath, err := filepath.Rel(targetDir, dep.ConfigPath)
	if err != nil {
		relPath = dep.ConfigPath // fallback to absolute
	}

	depBody.SetAttributeRaw(attrConfigPath, quotedStringTokens(relPath))

	// Copy all other attributes from source bytes (mock_outputs, etc.).
	for _, attr := range SortedAttributes(origBlock.Body.Attributes) {
		if attr.Name == attrConfigPath {
			continue
		}

		exprBytes := RangeBytes(srcBytes, attr.Expr.Range())
		depBody.SetAttributeRaw(attr.Name, RawTokens(exprBytes))
	}

	// Copy nested blocks within the dependency (if any).
	for _, nested := range origBlock.Body.Blocks {
		CopyBlockFromSource(depBody, nested, srcBytes)
	}
}

// writeNonDependencyContent writes non-dependency attributes and blocks from
// the autoinclude body. Each attribute expression is partially evaluated:
// resolvable parts (locals, pure refs) become literals, while deferred parts
// (dependency.*) keep their original source text. This enables mixed
// expressions like "${local.env}-${dependency.vpc.outputs.vpc_id}" to be
// partially resolved.
//
// Non-dependency blocks are always copied verbatim from source bytes.
func writeNonDependencyContent(outBody *hclwrite.Body, body *hclsyntax.Body, srcBytes []byte, evalCtx *hcl.EvalContext) {
	for _, attr := range SortedAttributes(body.Attributes) {
		if evalCtx == nil {
			exprBytes := RangeBytes(srcBytes, attr.Expr.Range())
			outBody.SetAttributeRaw(attr.Name, RawTokens(exprBytes))

			continue
		}

		result := PartialEval(attr.Expr, &EvalArgs{SrcBytes: srcBytes, EvalCtx: evalCtx, Deferred: deferredRoots})
		outBody.SetAttributeRaw(attr.Name, RawTokens(result))
	}

	for _, block := range body.Blocks {
		if block.Type == blockDependency {
			continue
		}

		CopyBlockFromSource(outBody, block, srcBytes)
	}
}

// CopyBlockFromSource copies a block from the original AST to hclwrite output,
// using source bytes for all attribute expressions.
//
// TODO: Non-dependency blocks containing local.* references are currently
// copied verbatim without evaluation. A future improvement should apply
// partial evaluation to nested block attributes as well.
func CopyBlockFromSource(outBody *hclwrite.Body, block *hclsyntax.Block, srcBytes []byte) {
	newBlock := outBody.AppendNewBlock(block.Type, block.Labels)
	blockBody := newBlock.Body()

	for _, attr := range SortedAttributes(block.Body.Attributes) {
		exprBytes := RangeBytes(srcBytes, attr.Expr.Range())
		blockBody.SetAttributeRaw(attr.Name, RawTokens(exprBytes))
	}

	for _, nested := range block.Body.Blocks {
		CopyBlockFromSource(blockBody, nested, srcBytes)
	}
}

// FindBlock finds a block by type and first label in the AST body.
// Exported for reuse by callers that need to locate specific blocks in parsed HCL bodies.
func FindBlock(body *hclsyntax.Body, blockType, label string) *hclsyntax.Block {
	for _, block := range body.Blocks {
		if block.Type == blockType && len(block.Labels) > 0 && block.Labels[0] == label {
			return block
		}
	}

	return nil
}

// RangeBytes extracts the source bytes for the given range.
func RangeBytes(src []byte, r hcl.Range) []byte {
	start := r.Start.Byte
	end := r.End.Byte

	if start >= len(src) || end > len(src) || start >= end {
		return nil
	}

	return src[start:end]
}

// quotedStringTokens creates hclwrite tokens for a quoted string literal.
func quotedStringTokens(value string) hclwrite.Tokens {
	return hclwrite.TokensForValue(cty.StringVal(value))
}

// RawTokens wraps raw bytes as a single hclwrite token. hclwrite.Format
// will handle the final formatting of the output.
func RawTokens(b []byte) hclwrite.Tokens {
	if len(b) == 0 {
		return nil
	}

	return hclwrite.Tokens{
		{Type: hclsyntax.TokenIdent, Bytes: b},
	}
}

// CommentTokens creates a comment token for hclwrite.
func CommentTokens(text string) hclwrite.Tokens {
	return hclwrite.Tokens{
		{Type: hclsyntax.TokenComment, Bytes: []byte(text)},
	}
}

// SortedAttributes returns attributes in a deterministic order by source position.
func SortedAttributes(attrs hclsyntax.Attributes) []*hclsyntax.Attribute {
	sorted := make([]*hclsyntax.Attribute, 0, len(attrs))
	for _, attr := range attrs {
		sorted = append(sorted, attr)
	}

	slices.SortFunc(sorted, func(a, b *hclsyntax.Attribute) int {
		return a.SrcRange.Start.Byte - b.SrcRange.Start.Byte
	})

	return sorted
}
