package config_test

import (
	"path/filepath"
	"testing"

	inthclparse "github.com/gruntwork-io/terragrunt/internal/hclparse"
	"github.com/gruntwork-io/terragrunt/internal/vfs"
	"github.com/gruntwork-io/terragrunt/pkg/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestGenerateStackKeepsHandWrittenAutoIncludeFile pins that generation leaves an autoinclude file
// the unit source ships without the generated header in place when the unit block declares no
// autoinclude.
func TestGenerateStackKeepsHandWrittenAutoIncludeFile(t *testing.T) {
	t.Parallel()

	gen := generateStack(t, map[string]string{
		filepath.Join(enabledUnitSource, inthclparse.AutoIncludeFile): `
inputs = {
  name = "app"
}
`,
		config.DefaultStackFile: `
unit "app" {
  source = "` + enabledUnitSource + `"
  path   = "app"
}
`,
	})

	assert.True(t, gen.generated("app", inthclparse.AutoIncludeFile))
}

// TestGenerateStackRemovesAutoIncludeFileOpeningWithGeneratedHeaderPrefix pins that generation
// removes an autoinclude file whose first line opens with the generated header prefix, whatever
// follows it on the line.
func TestGenerateStackRemovesAutoIncludeFileOpeningWithGeneratedHeaderPrefix(t *testing.T) {
	t.Parallel()

	gen := generateStack(t, map[string]string{
		filepath.Join(enabledUnitSource, inthclparse.AutoIncludeFile): `# Generated by Terragrunt from autoinclude block. Do not edit manually.
inputs = {
  name = "app"
}
`,
		config.DefaultStackFile: `
unit "app" {
  source = "` + enabledUnitSource + `"
  path   = "app"
}
`,
	})

	require.True(t, gen.generated("app", config.DefaultTerragruntConfigPath))
	assert.False(t, gen.generated("app", inthclparse.AutoIncludeFile))
}

// TestGenerateStackRemovesAutoIncludeFileOfRemovedBlock pins that regenerating a stack whose
// autoinclude block was deleted removes the file the earlier run wrote for it.
func TestGenerateStackRemovesAutoIncludeFileOfRemovedBlock(t *testing.T) {
	t.Parallel()

	teamFiles := map[string]string{
		filepath.Join("stacks", "team", "units", "member", "main.tf"):                          "",
		filepath.Join("stacks", "team", "units", "member", config.DefaultTerragruntConfigPath): "",
		filepath.Join("stacks", "team", config.DefaultStackFile): `
unit "member" {
  source = "./units/member"
  path   = "member"
}
`,
	}

	testCases := []struct {
		name        string
		withBlock   string
		withoutIt   string
		autoInclude []string
	}{
		{
			name: "unit",
			withBlock: `
unit "repo" {
  source = "` + enabledUnitSource + `"
  path   = "repo"
}

unit "app" {
  source = "` + enabledUnitSource + `"
  path   = "app"

  autoinclude {
    dependency "repo" {
      config_path = unit.repo.path
    }
  }
}
`,
			withoutIt: `
unit "repo" {
  source = "` + enabledUnitSource + `"
  path   = "repo"
}

unit "app" {
  source = "` + enabledUnitSource + `"
  path   = "app"
}
`,
			autoInclude: []string{"app", inthclparse.AutoIncludeFile},
		},
		{
			name: "stack",
			withBlock: `
stack "team" {
  source = "` + enabledStackSource + `"
  path   = "team"

  autoinclude {
    unit "extra" {
      source = "./units/member"
      path   = "extra"
    }
  }
}
`,
			withoutIt: `
stack "team" {
  source = "` + enabledStackSource + `"
  path   = "team"
}
`,
			autoInclude: []string{"team", inthclparse.AutoIncludeStackFile},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			files := map[string]string{config.DefaultStackFile: tc.withBlock}
			for path, body := range teamFiles {
				files[path] = body
			}

			gen := generateStack(t, files)
			require.True(t, gen.generated(tc.autoInclude...))

			stackPath := filepath.Join(enabledStackDir, config.DefaultStackFile)
			require.NoError(t, vfs.WriteFile(gen.v.FS, stackPath, []byte(tc.withoutIt), 0o644))

			generateStackLevel(t, gen.v, stackPath)

			assert.False(t, gen.generated(tc.autoInclude...))
		})
	}
}
