// Command colorgen writes the static color table read at log-formatting time.
//
// lipgloss stays the source of truth. The table is whatever it renders today,
// captured once here instead of on every process start. Run `go generate
// ./pkg/log/format/options/...` after upgrading lipgloss. TestColorTableIsCurrent
// fails when the committed table and lipgloss disagree.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strconv"

	"github.com/gruntwork-io/terragrunt/pkg/log/format/options"
)

const (
	outputPath  = "colortable_gen.go"
	outputPerms = 0o644
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "colorgen:", err)
		os.Exit(1)
	}
}

func run() error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by colorgen. DO NOT EDIT.\n\n")
	buf.WriteString("package options\n\n")
	buf.WriteString("// colorPrefixes holds the escape sequence lipgloss opens each ColorValue with,\n")
	buf.WriteString("// indexed by the value. Every one closes with ColorReset.\n")
	buf.WriteString("// Regenerate with `go generate ./pkg/log/format/options/...`.\n")
	buf.WriteString("var colorPrefixes = [...]string{\n")

	for value, seq := range options.BuildColorTable() {
		if seq.Prefix == "" && seq.Suffix == "" {
			continue
		}

		// Dropping the suffix column only holds while lipgloss closes every style
		// with the one reset. Stop rather than write a table that loses a difference.
		if seq.Suffix != options.ColorReset {
			return fmt.Errorf(
				"color %d closes with %q, not the shared reset %q",
				value,
				seq.Suffix,
				options.ColorReset,
			)
		}

		fmt.Fprintf(&buf, "\t%d: %s,\n", value, strconv.Quote(seq.Prefix))
	}

	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}

	return os.WriteFile(outputPath, src, outputPerms)
}
