services:
  web:
    build: .
    volumes:
      # Bind mount the working dir for live reload
      - .:/app
      # Avoid mounting node_modules from host
      - /app/node_modules
    ports:
      # Astro dev server port
      - "4321:4321"
    environment:
      - NODE_ENV=development
