name: Flake
on:
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  test:
    name: Flake Test (${{ matrix.flake.name }})
    runs-on: ${{ matrix.flake.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        flake:
          - name: Ubuntu Base tests
            os: ubuntu
            count: 3
            timeout: 45m
          - name: macOS Base tests
            os: macos
            count: 3
            timeout: 45m
          - name: Windows Base tests
            os: windows
            count: 3
            timeout: 45m

    env:
      MISE_PROFILE: cicd

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use mise to install dependencies
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.5.12
        env:
          # Adding token here to reduce the likelihood of hitting rate limit issues.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Go Build Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-${{ matrix.flake.os }}-amd64

      - name: Windows Setup
        if: runner.os == 'Windows'
        run: pwsh -File ./.github/scripts/setup/windows-setup.ps1
        shell: pwsh

      - name: Run Tests
        id: run-tests
        run: |
          go test -v ./... -count=${COUNT} -timeout ${TIMEOUT} | tee test_output.log
          go-junit-report -set-exit-code < test_output.log > result.xml
        shell: bash
        env:
          # Adding token here to reduce the likelihood of hitting rate limit issues.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNT: ${{ matrix.flake.count }}
          TIMEOUT: ${{ matrix.flake.timeout }}

      - name: Upload Report (${{ matrix.flake.name }})
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-report-${{ matrix.flake.name }}
          path: result.xml

      - name: Display Test Results (${{ matrix.flake.name }})
        uses: mikepenz/action-junit-report@3a81627bfac62268172037048872e8ebd4207e6d # v6
        if: always()
        with:
          report_paths: result.xml
          detailed_summary: 'true'
          include_time_in_summary: 'true'
          group_suite: 'true'
