name: Markdown Lint

on:
  workflow_call:

jobs:
  markdownlint:
    name: Run Lint
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: |
            docs/**/*.md
