name: Markdown Lint

on:
  workflow_call:

jobs:
  markdownlint:
    name: Run Lint
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
        with:
          globs: |
            docs/**/*.md
