name: Markdown Lint

on:
  workflow_call:

jobs:
  markdownlint:
    name: Run Lint
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          globs: |
            docs/**/*.md
