name: Test Sign Binary

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test-sign-binary:
    name: Test Sign
    runs-on: macos-latest
    env:
      MISE_PROFILE: cicd
      GON_VERSION: v0.0.37

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/

      - name: Use mise to install dependencies
        uses: jdx/mise-action@v2
        with:
          version: 2025.4.4
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache gon binary
        id: cache-gon
        uses: actions/cache@v4
        with:
          path: gon
          key: gon-${{ env.GON_VERSION }}

      - name: Download gon release
        if: steps.cache-gon.outputs.cache-hit != 'true'
        run: |
          curl -L -o gon.zip https://github.com/Bearer/gon/releases/download/${GON_VERSION}/gon_macos.zip
          unzip gon.zip
          chmod +x gon

      - name: Move gon to system path
        run: |
          sudo mv gon /usr/local/bin/gon
          sudo chmod +x /usr/local/bin/gon

      - name: Run gon as test
        run: |
          gon --version

      - name: Show downloaded binary
        run: |
          ls -lh bin/
          file bin/terragrunt-darwin-amd64