name: Vend Check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  vend-check:
    name: Check vendored OpenTofu code matches vend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Use mise to install dependencies
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.5.12
        env:
          # Adding token here to reduce the likelihood of hitting rate limit issues.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run vend
        run: go run ./internal/vendored/opentofu/vend

      - name: Check for changes
        run: |
          changes=$(git status --porcelain -- internal/vendored/opentofu go.mod go.sum)
          if [ -n "$changes" ]; then
            echo "$changes"
            echo "::error::internal/vendored/opentofu does not match what vend generates. Please run 'go run ./internal/vendored/opentofu/vend' locally and commit the changes."
            exit 1
          fi
          echo "internal/vendored/opentofu matches what vend generates"
